name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter:
  uses-material-design: true
